// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: org.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_org_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_org_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_org_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_org_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_org_2eproto;
class Organisation;
struct OrganisationDefaultTypeInternal;
extern OrganisationDefaultTypeInternal _Organisation_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::Organisation* Arena::CreateMaybeMessage<::Organisation>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class Organisation final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Organisation) */ {
 public:
  inline Organisation() : Organisation(nullptr) {}
  ~Organisation() override;
  explicit constexpr Organisation(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Organisation(const Organisation& from);
  Organisation(Organisation&& from) noexcept
    : Organisation() {
    *this = ::std::move(from);
  }

  inline Organisation& operator=(const Organisation& from) {
    CopyFrom(from);
    return *this;
  }
  inline Organisation& operator=(Organisation&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Organisation& default_instance() {
    return *internal_default_instance();
  }
  static inline const Organisation* internal_default_instance() {
    return reinterpret_cast<const Organisation*>(
               &_Organisation_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Organisation& a, Organisation& b) {
    a.Swap(&b);
  }
  inline void Swap(Organisation* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Organisation* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Organisation* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Organisation>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Organisation& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Organisation& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Organisation* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Organisation";
  }
  protected:
  explicit Organisation(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUridicAdresFieldNumber = 2,
    kNameFieldNumber = 3,
    kDoingRoleFieldNumber = 4,
    kDateFieldNumber = 1,
    kEconomicDoingFieldNumber = 5,
  };
  // required string uridicAdres = 2;
  bool has_uridicadres() const;
  private:
  bool _internal_has_uridicadres() const;
  public:
  void clear_uridicadres();
  const std::string& uridicadres() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_uridicadres(ArgT0&& arg0, ArgT... args);
  std::string* mutable_uridicadres();
  PROTOBUF_NODISCARD std::string* release_uridicadres();
  void set_allocated_uridicadres(std::string* uridicadres);
  private:
  const std::string& _internal_uridicadres() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_uridicadres(const std::string& value);
  std::string* _internal_mutable_uridicadres();
  public:

  // required string name = 3;
  bool has_name() const;
  private:
  bool _internal_has_name() const;
  public:
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // optional string doingRole = 4;
  bool has_doingrole() const;
  private:
  bool _internal_has_doingrole() const;
  public:
  void clear_doingrole();
  const std::string& doingrole() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_doingrole(ArgT0&& arg0, ArgT... args);
  std::string* mutable_doingrole();
  PROTOBUF_NODISCARD std::string* release_doingrole();
  void set_allocated_doingrole(std::string* doingrole);
  private:
  const std::string& _internal_doingrole() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_doingrole(const std::string& value);
  std::string* _internal_mutable_doingrole();
  public:

  // required int32 date = 1;
  bool has_date() const;
  private:
  bool _internal_has_date() const;
  public:
  void clear_date();
  int32_t date() const;
  void set_date(int32_t value);
  private:
  int32_t _internal_date() const;
  void _internal_set_date(int32_t value);
  public:

  // optional bool economicDoing = 5;
  bool has_economicdoing() const;
  private:
  bool _internal_has_economicdoing() const;
  public:
  void clear_economicdoing();
  bool economicdoing() const;
  void set_economicdoing(bool value);
  private:
  bool _internal_economicdoing() const;
  void _internal_set_economicdoing(bool value);
  public:

  // @@protoc_insertion_point(class_scope:Organisation)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr uridicadres_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr doingrole_;
  int32_t date_;
  bool economicdoing_;
  friend struct ::TableStruct_org_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Organisation

// required int32 date = 1;
inline bool Organisation::_internal_has_date() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool Organisation::has_date() const {
  return _internal_has_date();
}
inline void Organisation::clear_date() {
  date_ = 0;
  _has_bits_[0] &= ~0x00000008u;
}
inline int32_t Organisation::_internal_date() const {
  return date_;
}
inline int32_t Organisation::date() const {
  // @@protoc_insertion_point(field_get:Organisation.date)
  return _internal_date();
}
inline void Organisation::_internal_set_date(int32_t value) {
  _has_bits_[0] |= 0x00000008u;
  date_ = value;
}
inline void Organisation::set_date(int32_t value) {
  _internal_set_date(value);
  // @@protoc_insertion_point(field_set:Organisation.date)
}

// required string uridicAdres = 2;
inline bool Organisation::_internal_has_uridicadres() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool Organisation::has_uridicadres() const {
  return _internal_has_uridicadres();
}
inline void Organisation::clear_uridicadres() {
  uridicadres_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& Organisation::uridicadres() const {
  // @@protoc_insertion_point(field_get:Organisation.uridicAdres)
  return _internal_uridicadres();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Organisation::set_uridicadres(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000001u;
 uridicadres_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Organisation.uridicAdres)
}
inline std::string* Organisation::mutable_uridicadres() {
  std::string* _s = _internal_mutable_uridicadres();
  // @@protoc_insertion_point(field_mutable:Organisation.uridicAdres)
  return _s;
}
inline const std::string& Organisation::_internal_uridicadres() const {
  return uridicadres_.Get();
}
inline void Organisation::_internal_set_uridicadres(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  uridicadres_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* Organisation::_internal_mutable_uridicadres() {
  _has_bits_[0] |= 0x00000001u;
  return uridicadres_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* Organisation::release_uridicadres() {
  // @@protoc_insertion_point(field_release:Organisation.uridicAdres)
  if (!_internal_has_uridicadres()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  auto* p = uridicadres_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (uridicadres_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    uridicadres_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void Organisation::set_allocated_uridicadres(std::string* uridicadres) {
  if (uridicadres != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  uridicadres_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), uridicadres,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (uridicadres_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    uridicadres_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Organisation.uridicAdres)
}

// required string name = 3;
inline bool Organisation::_internal_has_name() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool Organisation::has_name() const {
  return _internal_has_name();
}
inline void Organisation::clear_name() {
  name_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& Organisation::name() const {
  // @@protoc_insertion_point(field_get:Organisation.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Organisation::set_name(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000002u;
 name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Organisation.name)
}
inline std::string* Organisation::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:Organisation.name)
  return _s;
}
inline const std::string& Organisation::_internal_name() const {
  return name_.Get();
}
inline void Organisation::_internal_set_name(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* Organisation::_internal_mutable_name() {
  _has_bits_[0] |= 0x00000002u;
  return name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* Organisation::release_name() {
  // @@protoc_insertion_point(field_release:Organisation.name)
  if (!_internal_has_name()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  auto* p = name_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (name_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void Organisation::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (name_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Organisation.name)
}

// optional string doingRole = 4;
inline bool Organisation::_internal_has_doingrole() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool Organisation::has_doingrole() const {
  return _internal_has_doingrole();
}
inline void Organisation::clear_doingrole() {
  doingrole_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000004u;
}
inline const std::string& Organisation::doingrole() const {
  // @@protoc_insertion_point(field_get:Organisation.doingRole)
  return _internal_doingrole();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Organisation::set_doingrole(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000004u;
 doingrole_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Organisation.doingRole)
}
inline std::string* Organisation::mutable_doingrole() {
  std::string* _s = _internal_mutable_doingrole();
  // @@protoc_insertion_point(field_mutable:Organisation.doingRole)
  return _s;
}
inline const std::string& Organisation::_internal_doingrole() const {
  return doingrole_.Get();
}
inline void Organisation::_internal_set_doingrole(const std::string& value) {
  _has_bits_[0] |= 0x00000004u;
  doingrole_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* Organisation::_internal_mutable_doingrole() {
  _has_bits_[0] |= 0x00000004u;
  return doingrole_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* Organisation::release_doingrole() {
  // @@protoc_insertion_point(field_release:Organisation.doingRole)
  if (!_internal_has_doingrole()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000004u;
  auto* p = doingrole_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (doingrole_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    doingrole_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void Organisation::set_allocated_doingrole(std::string* doingrole) {
  if (doingrole != nullptr) {
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  doingrole_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), doingrole,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (doingrole_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    doingrole_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Organisation.doingRole)
}

// optional bool economicDoing = 5;
inline bool Organisation::_internal_has_economicdoing() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool Organisation::has_economicdoing() const {
  return _internal_has_economicdoing();
}
inline void Organisation::clear_economicdoing() {
  economicdoing_ = false;
  _has_bits_[0] &= ~0x00000010u;
}
inline bool Organisation::_internal_economicdoing() const {
  return economicdoing_;
}
inline bool Organisation::economicdoing() const {
  // @@protoc_insertion_point(field_get:Organisation.economicDoing)
  return _internal_economicdoing();
}
inline void Organisation::_internal_set_economicdoing(bool value) {
  _has_bits_[0] |= 0x00000010u;
  economicdoing_ = value;
}
inline void Organisation::set_economicdoing(bool value) {
  _internal_set_economicdoing(value);
  // @@protoc_insertion_point(field_set:Organisation.economicDoing)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_org_2eproto
